Removing opacity/hue adjustments on transparent
Fixed SCSS compilation errors since you cannot perform hue or alpha adjustments on the color `transparent`

Example from before which produced an error:

```$popover-border-color:                transparent;
$popover-arrow-outer-color:           fadein($popover-border-color, 7.5%);```